baseurl = "/"
copyright = "r-makino"
defaultContentLanguage = "ja"
disableKinds = []
enableEmoji = false
enableInlineShortcodes = false
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = true
languageCode = "ja-JP"
paginate = 6
title = "Tech Blog"
